// Korean names for every polygon on the world map, keyed by the English name
// used in geo-data.js. The hover label reads from here, so countries without
// authored content still show a name when you point at them.
window.SE_WORLD_NAME_KO = {
  "Fiji": "피지",
  "United Republic of Tanzania": "탄자니아",
  "Western Sahara": "서사하라",
  "Canada": "캐나다",
  "United States of America": "미국",
  "Kazakhstan": "카자흐스탄",
  "Uzbekistan": "우즈베키스탄",
  "Papua New Guinea": "파푸아뉴기니",
  "Indonesia": "인도네시아",
  "Argentina": "아르헨티나",
  "Chile": "칠레",
  "Democratic Republic of the Congo": "콩고민주공화국",
  "Somalia": "소말리아",
  "Kenya": "케냐",
  "Sudan": "수단",
  "Chad": "차드",
  "Haiti": "아이티",
  "Dominican Republic": "도미니카공화국",
  "Russia": "러시아",
  "The Bahamas": "바하마",
  "Falkland Islands": "포클랜드 제도",
  "Norway": "노르웨이",
  "Greenland": "그린란드",
  "French Southern and Antarctic Lands": "프랑스령 남방·남극 지역",
  "East Timor": "동티모르",
  "South Africa": "남아프리카공화국",
  "Lesotho": "레소토",
  "Mexico": "멕시코",
  "Uruguay": "우루과이",
  "Brazil": "브라질",
  "Bolivia": "볼리비아",
  "Peru": "페루",
  "Colombia": "콜롬비아",
  "Panama": "파나마",
  "Costa Rica": "코스타리카",
  "Nicaragua": "니카라과",
  "Honduras": "온두라스",
  "El Salvador": "엘살바도르",
  "Guatemala": "과테말라",
  "Belize": "벨리즈",
  "Venezuela": "베네수엘라",
  "Guyana": "가이아나",
  "Suriname": "수리남",
  "France": "프랑스",
  "Ecuador": "에콰도르",
  "Puerto Rico": "푸에르토리코",
  "Jamaica": "자메이카",
  "Cuba": "쿠바",
  "Zimbabwe": "짐바브웨",
  "Botswana": "보츠와나",
  "Namibia": "나미비아",
  "Senegal": "세네갈",
  "Mali": "말리",
  "Mauritania": "모리타니",
  "Benin": "베냉",
  "Niger": "니제르",
  "Nigeria": "나이지리아",
  "Cameroon": "카메룬",
  "Togo": "토고",
  "Ghana": "가나",
  "Ivory Coast": "코트디부아르",
  "Guinea": "기니",
  "Guinea-Bissau": "기니비사우",
  "Liberia": "라이베리아",
  "Sierra Leone": "시에라리온",
  "Burkina Faso": "부르키나파소",
  "Central African Republic": "중앙아프리카공화국",
  "Republic of the Congo": "콩고공화국",
  "Gabon": "가봉",
  "Equatorial Guinea": "적도기니",
  "Zambia": "잠비아",
  "Malawi": "말라위",
  "Mozambique": "모잠비크",
  "eSwatini": "에스와티니",
  "Angola": "앙골라",
  "Burundi": "부룬디",
  "Israel": "이스라엘",
  "Lebanon": "레바논",
  "Madagascar": "마다가스카르",
  "Palestine": "팔레스타인",
  "Gambia": "감비아",
  "Tunisia": "튀니지",
  "Algeria": "알제리",
  "Jordan": "요르단",
  "United Arab Emirates": "아랍에미리트",
  "Qatar": "카타르",
  "Kuwait": "쿠웨이트",
  "Iraq": "이라크",
  "Oman": "오만",
  "Vanuatu": "바누아투",
  "Cambodia": "캄보디아",
  "Thailand": "태국",
  "Laos": "라오스",
  "Myanmar": "미얀마",
  "Vietnam": "베트남",
  "North Korea": "북한",
  "South Korea": "대한민국",
  "Mongolia": "몽골",
  "India": "인도",
  "Bangladesh": "방글라데시",
  "Bhutan": "부탄",
  "Nepal": "네팔",
  "Pakistan": "파키스탄",
  "Afghanistan": "아프가니스탄",
  "Tajikistan": "타지키스탄",
  "Kyrgyzstan": "키르기스스탄",
  "Turkmenistan": "투르크메니스탄",
  "Iran": "이란",
  "Syria": "시리아",
  "Armenia": "아르메니아",
  "Sweden": "스웨덴",
  "Belarus": "벨라루스",
  "Ukraine": "우크라이나",
  "Poland": "폴란드",
  "Austria": "오스트리아",
  "Hungary": "헝가리",
  "Moldova": "몰도바",
  "Romania": "루마니아",
  "Lithuania": "리투아니아",
  "Latvia": "라트비아",
  "Estonia": "에스토니아",
  "Germany": "독일",
  "Bulgaria": "불가리아",
  "Greece": "그리스",
  "Turkey": "튀르키예",
  "Albania": "알바니아",
  "Croatia": "크로아티아",
  "Switzerland": "스위스",
  "Luxembourg": "룩셈부르크",
  "Belgium": "벨기에",
  "Netherlands": "네덜란드",
  "Portugal": "포르투갈",
  "Spain": "스페인",
  "Ireland": "아일랜드",
  "New Caledonia": "뉴칼레도니아",
  "Solomon Islands": "솔로몬 제도",
  "New Zealand": "뉴질랜드",
  "Australia": "오스트레일리아",
  "Sri Lanka": "스리랑카",
  "China": "중국",
  "Taiwan": "대만",
  "Italy": "이탈리아",
  "Denmark": "덴마크",
  "United Kingdom": "영국",
  "Iceland": "아이슬란드",
  "Azerbaijan": "아제르바이잔",
  "Georgia": "조지아",
  "Philippines": "필리핀",
  "Malaysia": "말레이시아",
  "Brunei": "브루나이",
  "Slovenia": "슬로베니아",
  "Finland": "핀란드",
  "Slovakia": "슬로바키아",
  "Czechia": "체코",
  "Eritrea": "에리트레아",
  "Japan": "일본",
  "Paraguay": "파라과이",
  "Yemen": "예멘",
  "Saudi Arabia": "사우디아라비아",
  "Antarctica": "남극",
  "Northern Cyprus": "북키프로스",
  "Cyprus": "키프로스",
  "Morocco": "모로코",
  "Egypt": "이집트",
  "Libya": "리비아",
  "Ethiopia": "에티오피아",
  "Djibouti": "지부티",
  "Somaliland": "소말릴란드",
  "Uganda": "우간다",
  "Rwanda": "르완다",
  "Bosnia and Herzegovina": "보스니아 헤르체고비나",
  "North Macedonia": "북마케도니아",
  "Republic of Serbia": "세르비아",
  "Montenegro": "몬테네그로",
  "Kosovo": "코소보",
  "Trinidad and Tobago": "트리니다드 토바고",
  "South Sudan": "남수단",
};
